# GitLab CI/CD 配置文件
stages:
  - test
  - build
  - security
  - deploy-dev
  - deploy-staging
  - deploy-prod

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  DOCKER_REGISTRY: "registry.gitlab.com"
  DOCKER_IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  KUBECONFIG: /tmp/kubeconfig

cache:
  paths:
    - .m2/repository/
    - target/

# 测试阶段
test:
  stage: test
  image: maven:3.8.4-openjdk-8
  script:
    - mvn clean test
    - mvn jacoco:report
  artifacts:
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
      coverage_report:
        coverage_format: jacoco
        path: "**/target/site/jacoco/jacoco.xml"
    paths:
      - target/
    expire_in: 1 hour
  coverage: '/Total.*?([0-9]{1,3})%/'

# 构建阶段
build:
  stage: build
  image: maven:3.8.4-openjdk-8
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - "*/target/*.jar"
    expire_in: 1 hour
  only:
    - develop
    - main
    - merge_requests

# 安全扫描
security_scan:
  stage: security
  image: maven:3.8.4-openjdk-8
  script:
    - mvn org.owasp:dependency-check-maven:check
  artifacts:
    reports:
      dependency_scanning: target/dependency-check-report.json
  allow_failure: true

# Docker镜像构建
build_docker_images:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # 构建管理服务镜像
    - docker build -t $CI_REGISTRY_IMAGE/pulse-manager:$CI_COMMIT_SHA -f scripts/docker/Dockerfile.manager .
    - docker push $CI_REGISTRY_IMAGE/pulse-manager:$CI_COMMIT_SHA
    
    # 构建应用服务镜像
    - docker build -t $CI_REGISTRY_IMAGE/pulse-app:$CI_COMMIT_SHA -f scripts/docker/Dockerfile.app .
    - docker push $CI_REGISTRY_IMAGE/pulse-app:$CI_COMMIT_SHA
    
    # 如果是主分支，同时推送latest标签
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        docker tag $CI_REGISTRY_IMAGE/pulse-manager:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/pulse-manager:latest
        docker push $CI_REGISTRY_IMAGE/pulse-manager:latest
        docker tag $CI_REGISTRY_IMAGE/pulse-app:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/pulse-app:latest
        docker push $CI_REGISTRY_IMAGE/pulse-app:latest
      fi
  only:
    - develop
    - main

# 部署到开发环境
deploy_dev:
  stage: deploy-dev
  image: bitnami/kubectl:latest
  before_script:
    - echo $KUBE_CONFIG_DEV | base64 -d > $KUBECONFIG
  script:
    - kubectl config use-context dev-cluster
    - kubectl set image deployment/pulse-manager-deployment pulse-manager=$CI_REGISTRY_IMAGE/pulse-manager:$CI_COMMIT_SHA -n pulse-dev
    - kubectl set image deployment/pulse-app-deployment pulse-app=$CI_REGISTRY_IMAGE/pulse-app:$CI_COMMIT_SHA -n pulse-dev
    - kubectl rollout status deployment/pulse-manager-deployment -n pulse-dev
    - kubectl rollout status deployment/pulse-app-deployment -n pulse-dev
  environment:
    name: development
    url: https://dev.pulse.example.com
  only:
    - develop

# 部署到预发布环境
deploy_staging:
  stage: deploy-staging
  image: bitnami/kubectl:latest
  before_script:
    - echo $KUBE_CONFIG_STAGING | base64 -d > $KUBECONFIG
  script:
    - kubectl config use-context staging-cluster
    - kubectl set image deployment/pulse-manager-deployment pulse-manager=$CI_REGISTRY_IMAGE/pulse-manager:$CI_COMMIT_SHA -n pulse-staging
    - kubectl set image deployment/pulse-app-deployment pulse-app=$CI_REGISTRY_IMAGE/pulse-app:$CI_COMMIT_SHA -n pulse-staging
    - kubectl rollout status deployment/pulse-manager-deployment -n pulse-staging
    - kubectl rollout status deployment/pulse-app-deployment -n pulse-staging
  environment:
    name: staging
    url: https://staging.pulse.example.com
  when: manual
  only:
    - main

# 部署到生产环境
deploy_prod:
  stage: deploy-prod
  image: bitnami/kubectl:latest
  before_script:
    - echo $KUBE_CONFIG_PROD | base64 -d > $KUBECONFIG
  script:
    - kubectl config use-context prod-cluster
    - kubectl set image deployment/pulse-manager-deployment pulse-manager=$CI_REGISTRY_IMAGE/pulse-manager:$CI_COMMIT_SHA -n pulse-prod
    - kubectl set image deployment/pulse-app-deployment pulse-app=$CI_REGISTRY_IMAGE/pulse-app:$CI_COMMIT_SHA -n pulse-prod
    - kubectl rollout status deployment/pulse-manager-deployment -n pulse-prod
    - kubectl rollout status deployment/pulse-app-deployment -n pulse-prod
  environment:
    name: production
    url: https://pulse.example.com
  when: manual
  only:
    - main